/// Flutter icons MyCustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomIcons
///      fonts:
///       - asset: fonts/MyCustomIcons.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyCustomIcons';
  static const _kFontPkg = null;

  static const IconData box = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_shopping_cart = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airport_shuttle = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_shipping = IconData(0xe9f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xea3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_active = IconData(0xea3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xea5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_outline = IconData(0xea5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_drop = IconData(0xea80, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place = IconData(0xea81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData room = IconData(0xeabd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_module = IconData(0xeb7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = IconData(0xebff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = IconData(0xec00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode = IconData(0xec34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xec35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xec3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xec3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xec43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_1 = IconData(0xec83, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_1 = IconData(0xec88, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_2 = IconData(0xec89, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup = IconData(0xec8c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_1 = IconData(0xec8d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_2 = IconData(0xec98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_1 = IconData(0xec9f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login_1 = IconData(0xeca2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_1 = IconData(0xeca3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_4 = IconData(0xeca9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open_1 = IconData(0xecba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open_1 = IconData(0xecbb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open_mini = IconData(0xecbe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open_mini = IconData(0xecbf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open_big = IconData(0xecc2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open_big = IconData(0xecc3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_1 = IconData(0xecfd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_1 = IconData(0xed15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone_1 = IconData(0xed18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_outline = IconData(0xed3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_2 = IconData(0xed3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture_outline = IconData(0xed48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture_2 = IconData(0xed49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outline = IconData(0xed64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_3 = IconData(0xed65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_outline = IconData(0xed83, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_3 = IconData(0xed84, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_outline = IconData(0xed85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_2 = IconData(0xed86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_outline = IconData(0xed97, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_2 = IconData(0xed98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_2 = IconData(0xed9d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_add = IconData(0xeda0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_2 = IconData(0xedb2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open_outline = IconData(0xedce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open_2 = IconData(0xedcf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open_outline = IconData(0xedd0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open_2 = IconData(0xedd1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_2 = IconData(0xedd3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_2 = IconData(0xedd4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_3 = IconData(0xee9a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_inv = IconData(0xee9b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_alt = IconData(0xee9c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_4 = IconData(0xef12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_4 = IconData(0xef13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox_2 = IconData(0xef57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_3 = IconData(0xef58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_6 = IconData(0xef59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_1 = IconData(0xef5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_5 = IconData(0xef5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_left = IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right = IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox = IconData(0xf16b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_1 = IconData(0xf187, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_visa = IconData(0xf1f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_mastercard = IconData(0xf1f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_discover = IconData(0xf1f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_off = IconData(0xf204, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_on = IconData(0xf205, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xf290, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = IconData(0xf291, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
